const ADD_BOOK = 'ADD_BOOK';

const DELETE_BOOK = 'DELETE_BOOK';

const TAKE_CHANGE_DATA = 'TAKE_CHANGE_DATA';

const LOAD_LOCAL_STORAGE_DATA = 'LOAD_LOCAL_STORAGE_DATA';

const CHANGE_BOOK = 'CHANGE_BOOK';

export {ADD_BOOK, DELETE_BOOK, TAKE_CHANGE_DATA, LOAD_LOCAL_STORAGE_DATA, CHANGE_BOOK}