const ADD_BOOK = 'ADD_BOOK';
const DELETE_BOOK = 'DELETE_BOOK';

const FORM_BOOK = 'FORM_BOOK';
const CLEAN_FORM = 'CLEAN_FORM';
const ERROR_ADD_BOOK = 'ERROR_ADD_BOOK';

const SELECT_BOOK = 'SELECT_BOOK';

const LOAD_LOCAL_STORAGE_DATA = 'LOAD_LOCAL_STORAGE_DATA';

const CHANGE_BOOK = 'CHANGE_BOOK';
const TAKE_CHANGE_FORM = 'TAKE_CHANGE_FORM';

export {ADD_BOOK, DELETE_BOOK, SELECT_BOOK, LOAD_LOCAL_STORAGE_DATA, CHANGE_BOOK, FORM_BOOK, CLEAN_FORM, ERROR_ADD_BOOK, TAKE_CHANGE_FORM}
